spring.application.name=concert-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/concerttracker
spring.datasource.username=root
spring.datasource.password=yearup26
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create
